FROM node:20.10.0-alpine
WORKDIR /app
# Declarar ARGs y ENVs
ARG NEXT_PUBLIC_N8N_WEBHOOK_URL
ENV NEXT_PUBLIC_N8N_WEBHOOK_URL=${NEXT_PUBLIC_N8N_WEBHOOK_URL}

ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}

ARG NEXT_PUBLIC_RECAPTCHA_SECRET_KEY
ENV NEXT_PUBLIC_RECAPTCHA_SECRET_KEY=${NEXT_PUBLIC_RECAPTCHA_SECRET_KEY}

ARG NEXT_PUBLIC_RECAPTCHA_MIN_SCORE
ENV NEXT_PUBLIC_RECAPTCHA_MIN_SCORE=${NEXT_PUBLIC_RECAPTCHA_MIN_SCORE}

ARG NEXT_PUBLIC_GA_ID
ENV NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}

ARG NEXT_PUBLIC_GTM_ID
ENV NEXT_PUBLIC_GTM_ID=${NEXT_PUBLIC_GTM_ID}

ARG NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}

# Copiar solo package.json primero (mejor cache)
COPY package*.json ./
RUN npm install

# Ahora copiar el resto del código
COPY . .

# Build con las variables ya disponibles
RUN npm run build

EXPOSE 6115
CMD ["npm", "start"]
